language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
      env: IDEA_VERSION=IU-2018.3.6
    - os: linux
      jdk: openjdk11
      env: IDEA_VERSION=IU-2019.3.4
    - os: linux
      jdk: openjdk11
      env: IDEA_VERSION=IU-2020.1.2
    - os: linux
      jdk: openjdk11
      env: IDEA_VERSION=IU-LATEST-EAP-SNAPSHOT
  allow_failures:
    - env: IDEA_VERSION=IU-LATEST-EAP-SNAPSHOT

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
git:
  depth: 3

before_install:
  - chmod +x gradlew

script: "./gradlew clean buildPlugin test --warning-mode all -PdownloadIdeaSources=false"
