# see https://github.com/marketplace/actions/intellij-plugin-verifier
name: Plugin compatibility
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x.x
      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin -PdownloadIdeaSources=false
      - uses: thepieterdc/intellij-plugin-verifier-action@v1.1.2
        with:
          plugin: '/home/runner/work/intellij-extra-icons-plugin/intellij-extra-icons-plugin/build/distributions/*'
          versions: |
            2018.3.6
            2019.3.4
            2020.1
