#see https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action
name: Compatibility
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ide-versions: |
            ideaIC:2022.1.4
            ideaIU:2022.1.4
            ideaIC:2022.3
            ideaIU:2022.3
          failure-levels: | # see https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action#failure-levels
            OVERRIDE_ONLY_API_USAGES
            NON_EXTENDABLE_API_USAGES
            PLUGIN_STRUCTURE_WARNINGS
            INVALID_PLUGIN
          # TODO enable COMPATIBILITY_PROBLEMS when this issue is fixed: https://youtrack.jetbrains.com/issue/MP-4724/intellij-plugin-verifier-Plugin-AngularJS-doesnt-have-a-build-compatible-with-IC-222373954-in-Marketplace

      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
